apiVersion: v1
kind: Service
metadata:
  name: {{.Chart.Name}}
  labels:
    run: {{.Chart.Name}}
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
    - name: grpc
      port: 70
      protocol: TCP
      targetPort: 7070
  selector:
    app: {{.Chart.Name}}
