service:
  LOG_LEVEL: "debug"
  APPLICATION_ID: "tokenizer-gophercon"
  DEBUG_MODE_ENABLED: true
  REST_API_HTTP_ADDRESS: ":8080"
  REST_API_HTTP_TERMINATION_TIMEOUT: "5s"
  REST_API_HTTP_READ_REQUEST_TIMEOUT: "30s"
  REST_API_HTTP_WRITE_RESPONSE_TIMEOUT: "30s"
  TELEMETRY_JAEGER_ENDPOINT: "http://localhost:14268/api/traces"